// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_GEJyHZ3bhCiU78rTQqJsJ4vdfmPEMEg',
    appId: '1:915547304686:web:e0b1b4821632d7e36ef9ff',
    messagingSenderId: '915547304686',
    projectId: 'fp-ppb-9',
    authDomain: 'fp-ppb-9.firebaseapp.com',
    storageBucket: 'fp-ppb-9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdyYgaEpzMepJIru1DFEs32wBCnIDCVvI',
    appId: '1:915547304686:android:9c575324348c7af66ef9ff',
    messagingSenderId: '915547304686',
    projectId: 'fp-ppb-9',
    storageBucket: 'fp-ppb-9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAOfr-1kqqaajv4P1lUIpH62e1uX2-Qwk',
    appId: '1:915547304686:ios:28a5303e70272c7f6ef9ff',
    messagingSenderId: '915547304686',
    projectId: 'fp-ppb-9',
    storageBucket: 'fp-ppb-9.firebasestorage.app',
    iosBundleId: 'com.example.fpPpb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAOfr-1kqqaajv4P1lUIpH62e1uX2-Qwk',
    appId: '1:915547304686:ios:28a5303e70272c7f6ef9ff',
    messagingSenderId: '915547304686',
    projectId: 'fp-ppb-9',
    storageBucket: 'fp-ppb-9.firebasestorage.app',
    iosBundleId: 'com.example.fpPpb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_GEJyHZ3bhCiU78rTQqJsJ4vdfmPEMEg',
    appId: '1:915547304686:web:4c489ea6741cfff26ef9ff',
    messagingSenderId: '915547304686',
    projectId: 'fp-ppb-9',
    authDomain: 'fp-ppb-9.firebaseapp.com',
    storageBucket: 'fp-ppb-9.firebasestorage.app',
  );
}
